### ISSUE TITLE
Problem when compiling a library using a CMake and MinGW to use a functions.

### ISSUE THREAD

**Issue by ukicomputers** [OSWA00/pico-keypad4x4#1]
Hi @OSWA00. When compile library witch you created, to me shows a error. This is a error:
`c:/progra~2/gnuarm~1/102021~1.07/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: CMakeFiles/blink.dir/doorlock.cpp.obj: in function loop()':
doorlock.cpp:(.text._Z4loopv+0x10): undefined reference to pico_keypad_init(unsigned int*, unsigned int*, char*)'
c:/progra~2/gnuarm~1/102021~1.07/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: doorlock.cpp:(.text._Z4loopv+0x14): undefined reference to pico_keypad_get_key()'
c:/progra~2/gnuarm~1/102021~1.07/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: doorlock.cpp:(.text._Z4loopv+0x38): undefined reference to pico_keypad_get_key()'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [blink\CMakeFiles\blink.dir\build.make:871: blink/blink.elf] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:1439: blink/CMakeFiles/blink.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2`

Compiler shows a error to library don't have a functions of your library. How to reslove that? Thanks advance, @OSWA00.

**Comment by hhoswaldo** [comment]
Hey, when adding this to your CMake
`# Link required libraries to main executable
target_link_libraries(main
    keypad_4x4
)`
Change main to the name of your executable. 

E.g.
if your main function is in blink.c
`#Add executable
add_executable (blink
    src/blink.c
)

target_link_libraries(blink
    keypad_4x4
)
`

Greetings 😄
